name: Deploy PostgreSQL to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: modern-saga-472703-k3
        export_default_credentials: true

    - name: Install GKE auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials test-demo-cluster \
          --zone us-central1-a --project modern-saga-472703-k3

    - name: Deploy PostgreSQL to GKE
      run: |
        kubectl apply -f k8s/postgres-configmap.yaml --validate=false
        kubectl apply -f k8s/postgres-secret.yaml --validate=false
        kubectl apply -f k8s/postgres-deployment.yaml --validate=false
        kubectl apply -f k8s/postgres-service.yaml --validate=false
        kubectl get pods
        kubectl get svc
